#DO NOT USE TABS
url: http://emptysea.me
#port: 4000
baseurl: /
permalink: /:title.html

#destination: ./_site

markdown: redcarpet
redcarpet:
  extensions:
     - hard_wrap
     - no_intra_emphasis
     - autolink
     - strikethrough
     - disable_indented_code_blocks
     - fenced_code_blocks
